openapi: 3.0.0
info:
  title: mahjong-account-app-backend
  version: 1.0.0
  description: Lambda API for mahjong-account-app-backend(user management, rules, and matches).
paths:
  /hello:
    get:
      summary: hw
      responses:
        200:
          description: 'success'
      x-amazon-apigateway-integration:
        uri:
          Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${HelloWorldFunction.Arn}:dev/invocations
        passthroughBehavior: when_no_templates
        httpMethod: POST
        type: aws_proxy
