AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  HelloWorldApiGatewayApi

  Sample SAM Template for HelloWorldApiGatewayApi

Parameters:
  StageName:
    Type: String
    AllowedValues:
      - dev
      - prod
      - local
    Default: dev
    Description: Stage name for the deployment
Mappings:
  StageMap:
    dev:
      stage: dev
      apipath: /dev
    prod:
      stage: dev
      apipath: /prod
    local:
      stage: local
      apipath: /prod
Conditions:
  IsDev: !Equals [!Ref StageName, dev]
  IsProd: !Equals [!Ref StageName, prod]
  IsLocal: !Equals [!Ref StageName, local]
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3
    MemorySize: 128

    Tracing: Active
  Api:
    TracingEnabled: true
Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: hello_world/
      AutoPublishAlias: dev
      Handler: app.lambda_handler
      Runtime: python3.9
      Architectures:
      - x86_64
      Policies:
        DynamoDBCrudPolicy:
          TableName: *
      Environment:
        Variables:
          TABLE_NAME: !FindInMap [StageMap, !Ref StageName, stage]
      Events:
        HelloWorld:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: "/hello"
            Method: get
  DynamoDBTableDev:
    Type: AWS::DynamoDB::Table
    Condition: IsDev
    Properties:
      TableName: dynamodb-table-dev
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: date
          AttributeType: N
      KeySchema:
        - AttributeName: id
          KeyType: HASH
        - AttributeName: date
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      StreamSpecification:
        StreamViewType: NEW_IMAGE
  DynamoDBTableProd:
    Type: AWS::DynamoDB::Table
    Condition: IsProd
    Properties:
      TableName: dynamodb-table-prod
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: date
          AttributeType: N
      KeySchema:
        - AttributeName: id
          KeyType: HASH
        - AttributeName: date
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      StreamSpecification:
        StreamViewType: NEW_IMAGE

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  HelloWorldApi:
    Description: API Gateway endpoint URL for Prod stage for Hello World function
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  HelloWorldFunction:
    Description: Hello World Lambda Function ARN
    Value: !GetAtt HelloWorldFunction.Arn
  HelloWorldFunctionIamRole:
    Description: Implicit IAM Role created for Hello World function
    Value: !GetAtt HelloWorldFunctionRole.Arn
